name: Run build

on:
  pull_request:
    branches:
    - main

jobs:
  build: 
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    name: build
    runs-on: ${{matrix.os}}
    steps:
    - uses: actions/checkout@v4
    - name: npm install, build and test
      run: |
        npm install
        npm run build --if-present
